name: Test Windows Runner on Issue Creation

on:
  push:
    branches: 
      - main

jobs:
  test-windows-runner:
    runs-on: [ritesh]
    steps:
      - name: Show basic info
        run: echo "Issue triggered workflow on Windows runner"

      - name: Print system info
        run: systeminfo

      - name: List current directory
        run: dir

      - name: Confirm runner
        run: echo "Runner working"
