name: Test Windows Runner on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  test-windows-runner:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Show basic info
        run: echo "Issue triggered workflow on Windows runner"

      - name: Print system info
        run: systeminfo

      - name: List current directory
        run: dir

      - name: Confirm runner
        run: echo "Runner working"
